# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TCOpenCVApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TCOpenCVApp
  pod 'OpenCV', '~> 3.4.2'

  target 'TCOpenCVAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TCOpenCVAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
